- name: Update GitOps repository
  env:
    GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
    IMAGE_TAG: ${{ github.sha }}
  run: |
    git clone https://x-access-token:${GITOPS_TOKEN}@github.com/mekkiamine/E-ComK8s.git gitops

    cd gitops

    git config user.name "github-actions[bot]"
    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    sed -i \
      "s|image: mendax1/e-comfront:.*|image: mendax1/e-comfront:${IMAGE_TAG}|" \
      apps/frontend/deployment.yaml

    git add apps/frontend/deployment.yaml

    git commit -m "update frontend image to ${IMAGE_TAG}" || echo "No changes to commit"

    git push origin main

